# Generated by Django 5.2.6 on 2025-09-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAttachment',
        ),
    ]
